const jCategory = [
  {
    index: "0",
    image: "../images/google.png",
    title: "Web Developer",
    rate: "$900 - 1200/m",
    av: "Full Time",
    companyName: "Google",
    location: "USA",
    vacancy: "01",
    hours: "50h / week",
    description:
      "We are looking for a talented Frontend Web Developer to join our team. You will work closely with the design and backend teams to build responsive and modern web applications using HTML, CSS, and JavaScript. Experience with frameworks like React or Vue is a plus.",
    skills: " HTML, CSS, JavaScript, React.js, Git, REST APIs",
    status: "Full Time",
    workplace: "Work from home",
    education: "Bachelor’s degree in Computer Science, IT, or related field",
    experience: "1 – 3 years of experience in frontend development",
  },
  {
    index: "1",
    image: "../images/uber.png",
    title: "Business Associate",
    rate: "$700 - 1000/m",
    av: "Part Time",
    companyName: "Uber",
    location: "Bengaluru, India",
    vacancy: "20",
    hours: "45h / week",
    description:
      "As a Business Associate, you’ll assist in market analysis, reporting, and operations support. A great opportunity to gain startup experience and sharpen analytical thinking.",
    skills: "MS Excel, Business Analytics, Communication ",
    status: "Part Time",
    workplace: "Work from home",
    education: "Bachelor’s degree in Business Administration or Marketing",
    experience: "Final-year students are also welcome",
  },
  {
    index: "2",
    image: "../images/linkedin.png",
    title: "Data Analyst",
    rate: "$800 - 1100/m",
    av: "Freelancer",
    companyName: "LinkedIn",
    location: "Remote",
    vacancy: "50",
    hours: "55h / week",
    description:
      "Analyze trends, automate reports, and help stakeholders make data-driven decisions. You'll work with datasets, dashboards, and deliver insights.",
    skills: " SQL, Excel, Tableau/Power BI, Python basics",
    status: "Freelancer",
    workplace: "Remote",
    education: "B.Sc/B.Tech in Statistics, CS, or any quantitative field",
    experience: "Final-year students are also welcome. strong math foundation",
  },
  {
    index: "3",
    image: "../images/facebook.png",
    title: "Generative AI",
    rate: "$1200 - 1500/m",
    av: "Full Time",
    companyName: "Facebook",
    location: "Remote",
    vacancy: "40",
    hours: "55h / week",
    description:
      "Work on state-of-the-art AI models, including language and image generation systems. Help build the future of AI-based products.",
    skills: "Python, PyTorch, NLP, Transformers, GANs",
    status: "Full Time",
    workplace: "Remote",
    education: "B.Tech/M.Tech in AI, Data Science, or Computer Science",
    experience: "1 - 2 years.Freshers Welcome",
  },
  {
    index: "4",
    image: "../images/instagram.png",
    title: "Full Stack Developer",
    rate: "$1400 - 1700/m",
    av: "Part Time",
    companyName: "Instagram",
    location: " Hybrid (New York)",
    vacancy: "60",
    hours: "55h / week",
    description:
      "Build scalable web apps with modern frontend and backend stacks. You’ll lead feature development, debug production issues, and integrate APIs.",
    skills: " React, Node.js, Express, MongoDB, Git",
    status: "Part Time",
    workplace: "Hybrid",
    education: "B.Tech/M.Tech in AI, Data Science, or Computer Science",
    experience: "1 - 2 years",
  },
  {
    index: "5",
    image: "../images/apple.png",
    title: "Data Scientist",
    rate: "$1100 - 1300/m",
    av: "Freelancer",
    companyName: "Apple",
    location: " Remote",
    vacancy: "60",
    hours: "55h / week",
    description:
      "Use advanced analytics to solve real-world problems. You’ll work on predictive models, recommendations, and business intelligence.",
    skills: " Python, Scikit-Learn, Pandas, Machine Learning, SQL",
    status: "Freelancer",
    workplace: "Hybrid",
    education: "B.Tech/M.Tech in AI, Data Science, or Computer Science",
    experience: "3 - 5 years",
  },
    {
    index: "6",
    image: "../images/wordpress.png",
    title: "Backend Developer",
    rate: "$1100 - 1300/m",
    av: "Full Time",
    companyName: "Wordpress",
    location: " Remote",
    vacancy: "60",
    hours: "55h / week",
    description:
      "Use advanced analytics to solve real-world problems. You’ll work on predictive models, recommendations, and business intelligence.",
    skills: "  server-side logic, databases, APIs, and Node.js, Python, or Java to power web ",
    status: "Full Time",
    workplace: "Hybrid",
    education: "B.Tech/M.Tech in AI, Data Science, or Computer Science",
    experience: "3 - 5 years",
  },
      {
    index: "7",
    image: "../images/yahoo.png",
    title: "AI Developer",
    rate: "$1100 - 1300/m",
    av: "Full Time",
    companyName: "Yahoo",
    location: " Remote",
    vacancy: "60",
    hours: "55h / week",
    description:
      "Use advanced analytics to solve real-world problems. You’ll work on predictive models, recommendations, and business intelligence.",
    skills: " Python, Scikit-Learn, Pandas, Machine Learning, SQL",
    status: "Full Time",
    workplace: "Hybrid",
    education: "B.Tech/M.Tech in AI, Data Science, or Computer Science",
    experience: "3 - 5 years",
  },
];
